### ISSUE TITLE
Sample files wont run

### ISSUE THREAD

**Issue by on6qd** [dashdotrobot/bike-wheel-calc#9]
Extract from **example_stand_on_spokes.py**

import bikewheelcalc as **bc**
wheel.hub = **wheel**.Hub(diam1=0.04, width1=0.03)

produces: **AttributeError: BicycleWheel instance has no attribute 'Hub'**

corrected to:

wheel.hub = **bc**.Hub(diam1=0.04, width1=0.03)

**Comment by dashdotrobot** [comment]
Functionality broken by #7. I'll get to this today or tomorrow.

**Comment by dashdotrobot** [comment]
Fixed with Pull Request #11.
